### ISSUE TITLE
Add seasonal component to state-space model.

### ISSUE THREAD

**Issue by tcassou** [tcassou/causal_impact#1]
* Refer to [this paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/41854.pdf) for further documentation
* Use a dedicated set of arguments in the `CausalImpact` constructor

**Comment by dberger1989** [comment]
Hi @tcassou, I see you switched from PyMC to statsmodels. For my own edification would you mind explaining that decision?

**Comment by tcassou** [comment]
Hi @dberger1989,

And thanks for your note.

There were a few reasons, the main one being that `statsmodels` implements the exact state space model I was looking for.
On top of that, specifying it with `PyMC` turned out to be less straightforward (in particular for the seasonal component), and ended up being slow / not converging very well.

It could be that I missed simple ways of doing it though, so if you have something in mind feel free to send a pull request, I like the flexibility of PyMC!

Thomas
